json.id           post.obj_key
json.title        post.to_title
json.published_at post.published_at
json.teaser       post.teaser.html_safe
json.body         post.body.html_safe
json.permalink    post.remote_link_path
json.thumbnail    post.asset.lsquare.tag
json.byline       post.byline
json.edit_path    post.admin_edit_path
