development: &development
  adapter: mysql2
  database: audio_vision
  username: root
  password: 

test:
  adapter: mysql2
  database: audio_vision_test
  username: root
  password: 

production:
  <<: *development

staging:
  <<: *development


# Mercer
mercer_development: &mercer_development
  adapter: mysql2
  database: mercer
  username: root
  password: 

mercer_test:
  adapter: mysql2
  database: mercer_test
  username: root
  password: 

mercer_staging:
  <<: *mercer_development

mercer_production:
  <<: *mercer_development
