development: &development
  adapter: mysql2
  database: audio_vision
  username: root
  password: 

test:
  adapter: mysql2
  database: audio_vision_test
  username: root
  password: 

production:
  <<: *development

staging:
  <<: *development
